openapi: 3.0.1
info:
  title: L0 Index
  description: Index Service
  license:
    name: MIT
    url: https://github.com/tiki/l0-index/blob/main/LICENSE
  version: 0.0.1
servers:
- url: https://index.l0.mytiki.com
paths:
  /api/latest/report:
    post:
      tags:
      - REPORT
      summary: Report Block
      description: Report a new block creation to the index service
      operationId: l0-index-report-post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportAO'
        required: true
      responses:
        "200":
          description: OK
      security:
      - l0Storage: []
  /health:
    get:
      tags:
      - HEALTH
      summary: Health Check
      description: Get service status
      operationId: l0-index-health-get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                message: OK
  /api/latest/app/{id}:
    get:
      tags:
      - FIND
      summary: Page Addresses
      description: Get a page of addresses given an app id
      operationId: l0-index-app-get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 100
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppAO'
      security:
      - jwt: []
  /api/latest/app/{id}/address/{address}:
    get:
      tags:
      - FIND
      summary: Page Blocks
      description: Get a page of block hashes given an app id and address
      operationId: l0-index-address-get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: address
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 100
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressAO'
      security:
      - jwt: []
  /api/latest/app/{id}/address/{address}/block/{hash}:
    get:
      tags:
      - FIND
      summary: Get Block
      description: "Get a deserialized block given an app id, address, and block hash"
      operationId: l0-index-block-get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: address
        in: path
        required: true
        schema:
          type: string
      - name: hash
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockAO'
      security:
      - jwt: []
  /api/latest/app/{id}/address/{address}/block/{block-hash}/transaction/{txn-hash}:
    get:
      tags:
      - FIND
      summary: Get Transaction
      description: "Get a deserialized transaction given an app id, address, block\
        \ hash, and transaction hash"
      operationId: l0-index-txn-get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: address
        in: path
        required: true
        schema:
          type: string
      - name: block-hash
        in: path
        required: true
        schema:
          type: string
      - name: txn-hash
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxnAO'
      security:
      - jwt: []
components:
  schemas:
    ReportAO:
      type: object
      properties:
        apiId:
          type: string
        address:
          type: string
        block:
          type: string
        src:
          type: string
        transactions:
          type: array
          items:
            type: string
    ApiError:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
        detail:
          type: string
        help:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
    AddressPageAO:
      type: object
      properties:
        page:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalAddresses:
          type: integer
          format: int64
        addresses:
          type: array
          items:
            type: string
    AppAO:
      type: object
      properties:
        appId:
          type: string
        addresses:
          $ref: '#/components/schemas/AddressPageAO'
    AddressAO:
      type: object
      properties:
        appId:
          type: string
        address:
          type: string
        blocks:
          $ref: '#/components/schemas/BlockPageAO'
    BlockPageAO:
      type: object
      properties:
        page:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalHashes:
          type: integer
          format: int64
        hashes:
          type: array
          items:
            type: string
    BlockAO:
      type: object
      properties:
        apiId:
          type: string
        address:
          type: string
        hash:
          type: string
        url:
          type: string
        version:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        previous:
          type: string
        signature:
          type: string
        transactionRoot:
          type: string
        transactions:
          type: array
          items:
            type: string
    Consent:
      type: object
      allOf:
      - $ref: '#/components/schemas/TxnAOContents'
      - type: object
        properties:
          ownershipId:
            type: string
          destination:
            type: string
          about:
            type: string
          reward:
            type: string
          expiry:
            type: string
            format: date-time
    Ownership:
      type: object
      allOf:
      - $ref: '#/components/schemas/TxnAOContents'
      - type: object
        properties:
          source:
            type: string
          type:
            type: string
          origin:
            type: string
          about:
            type: string
          contains:
            type: string
    Raw:
      type: object
      allOf:
      - $ref: '#/components/schemas/TxnAOContents'
    TxnAO:
      type: object
      properties:
        apiId:
          type: string
        address:
          type: string
        block:
          type: string
        url:
          type: string
        hash:
          type: string
        version:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        assetRef:
          type: string
        signature:
          type: string
        contentSchema:
          type: string
        contents:
          oneOf:
          - $ref: '#/components/schemas/Consent'
          - $ref: '#/components/schemas/Ownership'
          - $ref: '#/components/schemas/Raw'
    TxnAOContents:
      type: object
      properties:
        raw:
          type: string
  securitySchemes:
    l0Storage:
      type: http
      scheme: basic
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
