name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  id-token: write

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test_and_push:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: pgtestpw
          POSTGRES_DB: l0_index
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'zulu'

      - name: Install CLI
        uses: dopplerhq/cli-action@v2

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Create Tables
        run: psql -h localhost -d l0_index -U tester -f database/create_tables.sql
        env:
          PGPASSWORD: pgtestpw

      - name: Maven Package L0 Index
        run: doppler run -c tst -- mvn clean package
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_ST }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Registry login
        run: doctl registry login --expiry-seconds 600

      - name: Mvn project version
        id: version
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: production
          push: true
          tags: |
            registry.digitalocean.com/tiki/l0-index:${{ steps.version.outputs.version }}
            registry.digitalocean.com/tiki/l0-index:latest
          build-args: |
            JAR_FILE=target/*.jar

    outputs:
      version: ${{ steps.version.outputs.version }}

  deploy_to_infra:
    runs-on: ubuntu-latest
    needs: test_and_push
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform Variables
        working-directory: ./infra
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          sem_ver = "${{ needs.test_and_push.outputs.version }}"
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt
        working-directory: infra

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: infra

  sentry_release:
    runs-on: ubuntu-latest
    needs: deploy_to_infra
    environment: Production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'my-tiki'
          SENTRY_PROJECT: 'l0-index'
        with:
          environment: public
          ignore_missing: true
          ignore_empty: true

  publish_docs:
    runs-on: ubuntu-latest
    needs: [ sentry_release, test_and_push ]
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OpenApi
        uses: readmeio/rdme@8.6.6
        with:
          rdme: openapi openapi.yaml --key=${{ secrets.README_API_KEY }} --id=63eb0b3c8850f60012d4bf13

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.test_and_push.outputs.version }}
