name: release

on:
  pull_request:
    branches:
      - main
#    types:
#      - closed

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bump_and_tag:
    #if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: pgtestpw
          POSTGRES_DB: l0_index
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'

      - name: Install CLI
        uses: dopplerhq/cli-action@v1

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Create Tables
        run: psql -h localhost -d l0_index -U tester -f database/create_tables.sql
        env:
          PGPASSWORD: pgtestpw

      - name: Maven Package L0 Index
        run: doppler run -c tst -- mvn clean package
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_ST }}

      - name: Bump Version
        id: bump-version
        uses: mike-audi/semantic-versioning-maven@1.0.0
        with:
          access-token: ${{ secrets.github_token }}
          version-prefix:
    outputs:
      version: ${{ steps.bump-version.outputs.new-version }}
  test_and_push:
    runs-on: ubuntu-latest
    needs: bump_and_tag
    environment: Production
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: pgtestpw
          POSTGRES_DB: l0_index
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'

      - name: Install CLI
        uses: dopplerhq/cli-action@v1

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Create Tables
        run: psql -h localhost -d l0_index -U tester -f database/create_tables.sql
        env:
          PGPASSWORD: pgtestpw

      - name: Maven Package L0 Index
        run: doppler run -c tst -- mvn clean package
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_ST }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            registry.digitalocean.com/tiki/l0-index
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Registry login
        run: doctl registry login --expiry-seconds 600

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: prod.dockerfile
          push: true
          tags: ${{ needs.bump_and_tag.outputs.version }}
          build-args: |
            JAR_FILE=target/*.jar
            DOPPLER_ST=${{ secrets.DOPPLER_ST }}
  deploy_to_infra:
    runs-on: ubuntu-latest
    needs: [ bump_and_tag, test_and_push ]
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform Variables
        working-directory: ./infra
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          sem_ver = "${{ needs.bump_and_tag.outputs.version }}"
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt
        working-directory: infra

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: infra
  sentry_release:
    runs-on: ubuntu-latest
    needs: [ deploy_to_infra ]
    environment: Production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'my-tiki'
          SENTRY_PROJECT: 'l0-index'
        with:
          environment: public
  publish_docs:
    runs-on: ubuntu-latest
    needs: [ sentry_release ]
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OpenApi
        uses: readmeio/rdme@8.4.0
        with:
          rdme: openapi docs/openapi.yaml --key=${{ secrets.README_API_KEY }} --id=63c6011fa9d9d30086fb6427

      - name: Release
        uses: softprops/action-gh-release@v1
